### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by nrgapple** [zzanehip/The-OldOS-Project#11]
Can you add screen shots to what it looks like the new users? Coming here from trending.

Really cool project!

**Comment by zzanehip** [comment]
Great idea!

**Comment by jerodsanto** [comment]
Agreed, screenshots would be great for the casually interested!

I just [linked this up in Changelog News](https://changelog.com/news/P5oo) and would happily include a screenshot if you had a good one ✊

**Comment by zzanehip** [comment]
Alrighty, added a section to the Readme with the marketing screenshots, and added the full res ones to the "Images" folder.
