### ISSUE TITLE
Safari only loads website on first page

### ISSUE THREAD

**Issue by hellojsna** [zzanehip/The-OldOS-Project#18]
https://user-images.githubusercontent.com/49427963/121764575-f06ea400-cb7f-11eb-873e-c827ba71a24a.mov

When I try to open a website in a new tab in Safari, it loads the page on first tab. 

- iOS 15 Dev beta 1
- self-signed IPA from github

**Comment by atrinh0** [comment]
Looks like this is still happening 🧐
