### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by antdude** [zzanehip/The-OldOS-Project#20]
Will it work in old iPhone 6+ (iOS v12.5.3)?

**Comment by atrinh0** [comment]
Project currently has a minimum target of `iOS 14.1`

<img width="132" alt="Screenshot 2021-06-12 at 10 23 32" src="https://user-images.githubusercontent.com/16542463/121771603-40417100-cb68-11eb-9a3a-0addc4d3ba20.png">

**Comment by antdude** [comment]
Thanks.
