### ISSUE TITLE
Unable to build on Xcode 12.3

### ISSUE THREAD

**Issue by Ifuxit** [zzanehip/The-OldOS-Project#27]
I really want to test OldOS, and the TestFlight is already full. I decided that I can build it with Xcode, so I removed Xcode 12.5 and downloaded 12.3, just as recommended. However, I only have a personal developer account, and I can't sign it. It throws this error: "Personal development teams, including {account name}, do not support the Access WiFi Information and Game Center capabilities.". Is there any workaround for this? I really want to install it to my device. Maybe its possible to make an IPA, and install it with Cydia impactor? Thanks

**Comment by GregorGott** [comment]
I had the same error, but you can delete them.
_OldOS > Targets > OldOS > Signing & Capabilities > Game Center > -_
Same for _Access WiFi Information_

![Bildschirmfoto 2021-06-12 um 11 48 13](https://user-images.githubusercontent.com/85785843/121772196-39b8f680-cb74-11eb-8494-a2eca376a2d4.png)

I hope it helps!

**Comment by Ifuxit** [comment]
Thanks! It worked perfectly, and I flashed it successfully to my iPhone.
