### ISSUE TITLE
Icon placement is a bit funky and some stuff is cut off

### ISSUE THREAD

**Issue by HunterBoy344** [zzanehip/The-OldOS-Project#31]
![image](https://user-images.githubusercontent.com/66140471/121776939-95c45080-cb5d-11eb-9476-585d14f0cb3f.png)
I'm using an iPhone 6S on iOS 14.6.

**Comment by zzanehip** [comment]
Yup, on the list, need to do some reworking for iPhone 6S sized devices.

**Comment by HunterBoy344** [comment]
Home Screen layout seems fixed after updating to Build 9.
![image](https://user-images.githubusercontent.com/66140471/121952503-5139e000-cd2a-11eb-9aa9-c9744e0925df.png)
