### ISSUE TITLE
Design error on Home-Button iPhones

### ISSUE THREAD

**Issue by TheBalkanDev** [zzanehip/The-OldOS-Project#45]
Hi,
I’ve sideloaded OldOS with AltStore and on my test iPhone (iPhone 6s) is looks like this, the Dock is very Buggy, I hink its because the Fake Home-Button.

And the bar on the Top is bigger, than normal im a App in OldOS

![E5A86680-BDA1-42EE-9957-A6139629D38B](https://user-images.githubusercontent.com/75144786/122547358-4c2da700-d030-11eb-85e6-450edee9c3f8.png)

**Comment by TheBalkanDev** [comment]
(im) I mean *in*

**Comment by HunterBoy344** [comment]
The latest self-singable IPA is for Build 7, and Build 9 fixed this. I recommend getting OldOS from TestFlight instead, which has Build 9.

**Comment by TheBalkanDev** [comment]
The Beta Test is full, but its not impossible I enjoy it
