### ISSUE TITLE
Can you Release Build 9 as .ipa and Suggestion

### ISSUE THREAD

**Issue by TheBalkanDev** [zzanehip/The-OldOS-Project#46]
I’ve sideloaded OldOS with AltStore, but Build 7 is buggy.
Can you Release the newest Build as .ipa file?
I would do it myself but I don’t have any Swift knowledge.

And can you make, that you can import music from the Files App into iPod App?

**Comment by HunterBoy344** [comment]
Good news: he released Build 10!
