### ISSUE TITLE
TestFlight App Has expired

### ISSUE THREAD

**Issue by 488315** [zzanehip/The-OldOS-Project#87]
![image](https://user-images.githubusercontent.com/19639817/219497150-832b7bd8-7269-423f-86c9-d0900e1f0509.png)

**Comment by scottbeamer** [comment]
Project has been abandoned.

**Comment by Lonschick** [comment]
> Project has been abandoned.
Nah we will get an Update...

**Comment by 488315** [comment]
> > Project has been abandoned.
> 
> Nah we will get an Update...

I dont think so, this project has not been updated 2 years ago. I will close this issue.
